[general]
resource_parser_url = https://raw.githubusercontent.com/KOP-XIAO/QuantumultX/master/Scripts/resource-parser.js

[host]
ark.cn-beijing.volces.com = 173.254.212.158

[rewrite_remote]
https://raw.githubusercontent.com/Leslie159357/loon-plugin/main/MN-AI-Proxy.qxrewrite

[mitm]
hostname = ark.cn-beijing.volces.com
